import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { ConnectKitButton } from 'connectkit';
import { Hero } from '../../components/Hero';
import { Header } from '../../components/Header';
import { Subscriptions } from '../../components/Subscriptions';
import Layout from '../../components/Layout';
import { gql, useQuery } from 'urql';

const TodosQuery = gql`
{
    planCreateds {
      id
      name
      planId
      blockNumber
      blockTimestamp
      duration
      price
      transactionHash
    }
  }
`;

import { UsersSideNav } from '~~/components/UsersSideNav';

const Home: NextPage = () => {

    const [result, reexecuteQuery] = useQuery({
        query: TodosQuery,
      });
    
      const { data, fetching, error } = result;
      console.log(data);
      if (fetching) return <p>Loading...</p>;
      if (error) return <p>Oh no... {error.message}</p>;


    return (
        <div>
            <Head>
                <title>Multi Pay</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main>
                <Layout>
                    <div className="flex flex-row">
                        <UsersSideNav />
                        <Subscriptions />
                    <div>
                    {data.planCreateds.map((plan : any, id: number)=>{
                        return <div key={id}>
                            <h1>{plan.id}</h1>
                        <h1>{plan.name}</h1>
                        <h1>{plan.blockNumber}</h1>
                        <h1>{plan.blockTimestamp}</h1>
                        <h1>{plan.duration}</h1>
                        <h1>{plan.price}</h1>
                        <h1>{plan.transactionHash}</h1>
                        <h1>{plan.planId}</h1>
                        </div>
                    })}
                </div>
                    </div>
                </Layout>
            </main>
        </div>
    );
};

export default Home;
