import { useContext } from "react";
import Head from "next/head";
import Layout from "../../components/Layout";
import type { NextPage } from "next";
import { Link } from "react-router-dom";
import { SmartAccountContext } from "~~/context/SmartAccount";

const Home: NextPage = () => {
  const { address } = useContext(SmartAccountContext);

  if (address == null) {
    return (
      <div>
        <Head>
          <title>Multi Pay</title>
          <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
          <link href="/favicon.ico" rel="icon" />
        </Head>
        <main>
          You need to Login First. Go back <Link href="/">Home</Link>
        </main>
      </div>
    );
  }
  return (
    <div>
      <Head>
        <title>Multi Pay</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <Layout></Layout>
      </main>
    </div>
  );
};

export default Home;
