import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { ConnectKitButton } from 'connectkit';
import { Header } from '../../components/Header';
import { Subscribe } from '../../components/Subscribe';
import { CreatePlan } from '../../components/CreatePlan';
import Layout from '../../components/Layout';
import { CompanySideNav } from '~~/components/CompanySideNav';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Multi Pay</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main>
                <Layout>
                <div className="flex flex-row">
                    <CompanySideNav />
                    <CreatePlan />
                </div>
                </Layout>
            </main>
        </div>
    );
};

export default Home;
