import Head from "next/head";
import { Hero } from "../../components/Hero";
import Layout from "../../components/Layout";
import type { NextPage } from "next";
import { CompanySideNav } from "~~/components/CompanySideNav";

import { gql, useQuery } from 'urql';

const TodosQuery = gql`
{
    planCreateds {
      id
      name
      planId
      blockNumber
      blockTimestamp
      duration
      price
      transactionHash
    }
  }
`;
    

import { gql, useQuery } from 'urql';

const TodosQuery = gql`
{
    planCreateds {
      id
      name
      planId
      blockNumber
      blockTimestamp
      duration
      price
      transactionHash
    }
  }
`;
    

const Home: NextPage = () => {
  const [result, reexecuteQuery] = useQuery({
    query: TodosQuery,
  });

  const { data, fetching, error } = result;
  console.log(data);
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;
  return (
    <div>
      <Head>
        <title>Multi Pay</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <Layout>
          <div className="flex flex-row">
            <CompanySideNav />
            <Hero />
          <div className="w-[1200px] mx-auto mt-[20px]">
            <h1 className="text-[20px] font-[700]">Available Plans</h1>
                    {data.planCreateds.map((plan : any, id: number)=>{
                        return <div key={id}>
                        <h1>Plan Name: {plan.name}</h1>
                        <h1>Plan ID: {plan.planId}</h1>
                        <h1>Plan Duration: {plan.duration} month</h1>
                        <h1>Plan Price: {plan.price}</h1>
                        </div>
                    })}
              <h1 className="text-[20px] font-[700] mt-[20px]">Subcriber lists</h1>
                </div>
          </div>
        </Layout>
      </main>
    </div>
  );
};

export default Home;
