import Head from "next/head";
import { Hero } from "../components/Hero";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Multi Pay</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <Hero />
      </main>
    </div>
  );
};

export default Home;
